name: HVCC

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['python:3.9-bookworm']
    container: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - name: Initialize lfs
        run: git lfs pull
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tox
        run: tox
